FAIT20/7/14  bug: 1ere lecture FormAnimal : race2 est vide car set appelé avant espece.set (donc combo race2 vide car avant signal OnEspeceChange) (pour race1 ok)==> revoir ordre dans table2widget

FAIT 18/7/14 bug champ "NULL" dans formulaire sauvegarde (animal) (mais pas dans database cf 2eme lecture client/animal)
bug : faire mise à jour nom animal dans la liste dans fenetre openvet lors modification animal


Fait 16/7/14 correction bug majeur :  table liée : client-animal-consultation Get(Champ) renvoie null pour animal car utilise self.dicoChamp de tableLiée au lieu de self.dicoChamp de la tableparent (type animal)

(bug : lors creation nouveau client, ok puis annule : pb liste client cf apres)
bug creation nouveau client : n'est pas affiché, + liste pas mise à jour

amelioration: nouveau client : décocher les cases (mauvais client , etc...)


MyWidgets MyComboBox ***********
   BUG++++++++   si création 2eme comboBox le 1er ne s'affiche pas bien (meme si combo differents ex comboville comboclient)
dès la creation d un 2eme combobox le 1er pb affichage du pop up (liste vide)
tests avec 2 combo ville : change model() sur un combo ok mais l'autre combo devient vide/
essai de faire heriter comboville1 comboville2 de mycombo1 mycombo2 : marche pas, suppression attribut de class TableVille /
utilisation 2 QSqlQueryModelVille1 et 2 /verifie que les 2 models et 2 view sont <> / deconnection signal OnEditTextChanged : le model ne change pas mais dès creation 2eme comboBox le 1er ne s'affiche pas bien (unqiqt pop up)
==> non résolu mais fonctionne bien avec un seul MyComboBox

1/    bcp d'exception :
exception _mysql_exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query') in <bound method Cursor.__del__ of <MySQLdb.cursors.Cursor object at 0x28aa850>> ignored
../
==> apparement sans conséquences / à revoir


2/ erreur lors des comparaisons dans core_consultation
/VetCore/Core_Consultation.py:154: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if len(res)==1 and res[0][0].decode(config.dbCodec)==self.Consultant:

  la comparaison échoue alors que l'égalitée est vraie !!!  (même erreur ligne 180)
  
>>> res[0][0].decode(config.dbCodec)
u'BAGAINI (veto) Fran\xe7ois'
>>> type(res[0][0].decode(config.dbCodec))
<type 'unicode'>
>>> self.Consultant
PyQt4.QtCore.QByteArray('BAGAINI (veto) Fran\xc3\xa7ois')
>>> type(self.Consultant)
<class 'PyQt4.QtCore.QByteArray'>
  
  ===> pb comparaison de type differents et convertion en unicode
  
3/ MessageBox (ligne 197): bug /// 
Le programme déboggué a déclenché l'exception :
TypeError
"QMessageBox.about(QWidget, QString, QString): argument 1 has unexpected type 'instance'"
Fichier: /home/yvon/Documents/programmation/openvet2/interface graphique/OpenVet270114/VetCore/Core_Consultation.py, Ligne: 197

====> this n'est pas une instance de type QTGUI  ==> remplacer par un print
